GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsImlhdCI6MTcxMjM3OTI5NCwiZXhwIjoxNzEyMzc5MzE0fQ.sZ7qPOJt3rl_NKZBvDge4_T1pN52jdjPeQqjF48uOJo

###
# POST http://localhost:5000/users
# Content-Type: application/json 
# {
#     "name": "John Two",
#     "email": "john2@gmail.com",
#     "password": "123456",
#     "confPassword": "123456"
# }

###
POST http://localhost:5000/login
Content-Type: application/json 

{
    "email": "john@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token
